

### chmod +x /home/shiny/connectscape/bash.sh    ## Run: ./bash.sh
# taskset --cpu-list 6 setsid /home/shiny/connectscape/bash.sh >/dev/null 2>&1 < /dev/null &
# taskset --cpu-list 1 setsid /home/shiny/connectscape/bashB.sh >/dev/null 2>&1 < /dev/null & # NO
# setsid taskset --cpu-list 1 /home/shiny/connectscape/bashB.sh >/dev/null 2>&1 < /dev/null & # NO
# setsid /home/shiny/connectscape/bashB.sh >/dev/null 2>&1 < /dev/null & # NO
# /home/shiny/connectscape/bashB.sh # yes
# /home/shiny/connectscape/bashB.sh > outputfile_for_stdout & # yes
# taskset --cpu-list 1 /home/shiny/connectscape/bashB.sh > outputfile_for_stdout & NO 
## https://askubuntu.com/questions/191709/how-to-run-a-program-as-a-service-silent



cd /home/shiny/UNICOR/unicor/
  
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py lcc_scenarioA.rip &> /home/shiny/data/log2UNIC_lcc_scenarioA.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py lcc_scenarioB.rip &> /home/shiny/data/log2UNIC_lcc_scenarioB.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py lcc_scenarioC.rip &> /home/shiny/data/log2UNIC_lcc_scenarioC.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py lcc_scenarioD.rip &> /home/shiny/data/log2UNIC_lcc_scenarioD.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py lcc_scenarioE.rip &> /home/shiny/data/log2UNIC_lcc_scenarioE.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py lcc_scenarioF.rip &> /home/shiny/data/log2UNIC_lcc_scenarioF.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py lcc_scenarioG.rip &> /home/shiny/data/log2UNIC_lcc_scenarioG.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py lcc_scenarioH.rip &> /home/shiny/data/log2UNIC_lcc_scenarioH.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py lcc_scenarioI.rip &> /home/shiny/data/log2UNIC_lcc_scenarioI.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py lcc_scenarioJ.rip &> /home/shiny/data/log2UNIC_lcc_scenarioJ.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py lcc_scenarioK.rip &> /home/shiny/data/log2UNIC_lcc_scenarioK.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py lcc_scenarioL.rip &> /home/shiny/data/log2UNIC_lcc_scenarioL.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py lcc_scenarioM.rip &> /home/shiny/data/log2UNIC_lcc_scenarioM.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py lcc_scenarioN.rip &> /home/shiny/data/log2UNIC_lcc_scenarioN.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py lcc_scenarioO.rip &> /home/shiny/data/log2UNIC_lcc_scenarioO.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py lcc_scenarioP.rip &> /home/shiny/data/log2UNIC_lcc_scenarioP.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py lcc_scenarioQ.rip &> /home/shiny/data/log2UNIC_lcc_scenarioQ.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py lcc_scenarioR.rip &> /home/shiny/data/log2UNIC_lcc_scenarioR.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py lcc_scenarioS.rip &> /home/shiny/data/log2UNIC_lcc_scenarioS.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py lcc_scenarioT.rip &> /home/shiny/data/log2UNIC_lcc_scenarioT.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py lcc_scenarioU.rip &> /home/shiny/data/log2UNIC_lcc_scenarioU.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py lcc_scenarioV.rip &> /home/shiny/data/log2UNIC_lcc_scenarioV.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py lcc_scenarioW.rip &> /home/shiny/data/log2UNIC_lcc_scenarioW.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py lcc_scenarioX.rip &> /home/shiny/data/log2UNIC_lcc_scenarioX.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py lcc_scenarioY.rip &> /home/shiny/data/log2UNIC_lcc_scenarioY.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py lcc_scenarioZ.rip &> /home/shiny/data/log2UNIC_lcc_scenarioZ.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py lcc_scenarioAA.rip &> /home/shiny/data/log2UNIC_lcc_scenarioAA.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py lcc_scenarioAB.rip &> /home/shiny/data/log2UNIC_lcc_scenarioAB.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py lcc_scenarioAC.rip &> /home/shiny/data/log2UNIC_lcc_scenarioAC.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py lcc_scenarioAD.rip &> /home/shiny/data/log2UNIC_lcc_scenarioAD.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py lcc_scenarioAE.rip &> /home/shiny/data/log2UNIC_lcc_scenarioAE.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py lcc_scenarioAF.rip &> /home/shiny/data/log2UNIC_lcc_scenarioAF.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py lcc_scenarioAG.rip &> /home/shiny/data/log2UNIC_lcc_scenarioAG.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py lcc_scenarioAH.rip &> /home/shiny/data/log2UNIC_lcc_scenarioAH.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py lcc_scenarioAI.rip &> /home/shiny/data/log2UNIC_lcc_scenarioAI.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py lcc_scenarioAJ.rip &> /home/shiny/data/log2UNIC_lcc_scenarioAJ.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py lcc_scenarioAK.rip &> /home/shiny/data/log2UNIC_lcc_scenarioAK.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py lcc_scenarioAL.rip &> /home/shiny/data/log2UNIC_lcc_scenarioAL.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py lcc_scenarioAM.rip &> /home/shiny/data/log2UNIC_lcc_scenarioAM.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py lcc_scenarioAN.rip &> /home/shiny/data/log2UNIC_lcc_scenarioAN.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py lcc_scenarioAO.rip &> /home/shiny/data/log2UNIC_lcc_scenarioAO.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py lcc_scenarioAP.rip &> /home/shiny/data/log2UNIC_lcc_scenarioAP.txt


taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/lcc.py /home/shiny/data/sabah_10.shp /home/shiny/data/size1.tif /home/shiny/data/out_lcc_scenarioA.tif 100000 2 100 1 &> /home/shiny/data/log2COLA_lcc_scenarioA.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/lcc.py /home/shiny/data/sabah_100.shp /home/shiny/data/size1.tif /home/shiny/data/out_lcc_scenarioB.tif 100000 2 100 1 &> /home/shiny/data/log2COLA_lcc_scenarioB.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/lcc.py /home/shiny/data/sabah_20.shp /home/shiny/data/size1.tif /home/shiny/data/out_lcc_scenarioC.tif 100000 2 100 1 &> /home/shiny/data/log2COLA_lcc_scenarioC.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/lcc.py /home/shiny/data/sabah_200.shp /home/shiny/data/size1.tif /home/shiny/data/out_lcc_scenarioD.tif 100000 2 100 1 &> /home/shiny/data/log2COLA_lcc_scenarioD.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/lcc.py /home/shiny/data/sabah_50.shp /home/shiny/data/size1.tif /home/shiny/data/out_lcc_scenarioE.tif 100000 2 100 1 &> /home/shiny/data/log2COLA_lcc_scenarioE.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/lcc.py /home/shiny/data/sabah_500.shp /home/shiny/data/size1.tif /home/shiny/data/out_lcc_scenarioF.tif 100000 2 100 1 &> /home/shiny/data/log2COLA_lcc_scenarioF.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/lcc.py /home/shiny/data/sabah_10.shp /home/shiny/data/size2.tif /home/shiny/data/out_lcc_scenarioG.tif 100000 2 100 1 &> /home/shiny/data/log2COLA_lcc_scenarioG.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/lcc.py /home/shiny/data/sabah_100.shp /home/shiny/data/size2.tif /home/shiny/data/out_lcc_scenarioH.tif 100000 2 100 1 &> /home/shiny/data/log2COLA_lcc_scenarioH.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/lcc.py /home/shiny/data/sabah_20.shp /home/shiny/data/size2.tif /home/shiny/data/out_lcc_scenarioI.tif 100000 2 100 1 &> /home/shiny/data/log2COLA_lcc_scenarioI.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/lcc.py /home/shiny/data/sabah_200.shp /home/shiny/data/size2.tif /home/shiny/data/out_lcc_scenarioJ.tif 100000 2 100 1 &> /home/shiny/data/log2COLA_lcc_scenarioJ.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/lcc.py /home/shiny/data/sabah_50.shp /home/shiny/data/size2.tif /home/shiny/data/out_lcc_scenarioK.tif 100000 2 100 1 &> /home/shiny/data/log2COLA_lcc_scenarioK.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/lcc.py /home/shiny/data/sabah_500.shp /home/shiny/data/size2.tif /home/shiny/data/out_lcc_scenarioL.tif 100000 2 100 1 &> /home/shiny/data/log2COLA_lcc_scenarioL.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/lcc.py /home/shiny/data/sabah_10.shp /home/shiny/data/size3.tif /home/shiny/data/out_lcc_scenarioM.tif 100000 2 100 1 &> /home/shiny/data/log2COLA_lcc_scenarioM.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/lcc.py /home/shiny/data/sabah_100.shp /home/shiny/data/size3.tif /home/shiny/data/out_lcc_scenarioN.tif 100000 2 100 1 &> /home/shiny/data/log2COLA_lcc_scenarioN.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/lcc.py /home/shiny/data/sabah_20.shp /home/shiny/data/size3.tif /home/shiny/data/out_lcc_scenarioO.tif 100000 2 100 1 &> /home/shiny/data/log2COLA_lcc_scenarioO.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/lcc.py /home/shiny/data/sabah_200.shp /home/shiny/data/size3.tif /home/shiny/data/out_lcc_scenarioP.tif 100000 2 100 1 &> /home/shiny/data/log2COLA_lcc_scenarioP.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/lcc.py /home/shiny/data/sabah_50.shp /home/shiny/data/size3.tif /home/shiny/data/out_lcc_scenarioQ.tif 100000 2 100 1 &> /home/shiny/data/log2COLA_lcc_scenarioQ.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/lcc.py /home/shiny/data/sabah_500.shp /home/shiny/data/size3.tif /home/shiny/data/out_lcc_scenarioR.tif 100000 2 100 1 &> /home/shiny/data/log2COLA_lcc_scenarioR.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/lcc.py /home/shiny/data/sabah_10.shp /home/shiny/data/size4.tif /home/shiny/data/out_lcc_scenarioS.tif 100000 2 100 1 &> /home/shiny/data/log2COLA_lcc_scenarioS.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/lcc.py /home/shiny/data/sabah_100.shp /home/shiny/data/size4.tif /home/shiny/data/out_lcc_scenarioT.tif 100000 2 100 1 &> /home/shiny/data/log2COLA_lcc_scenarioT.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/lcc.py /home/shiny/data/sabah_20.shp /home/shiny/data/size4.tif /home/shiny/data/out_lcc_scenarioU.tif 100000 2 100 1 &> /home/shiny/data/log2COLA_lcc_scenarioU.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/lcc.py /home/shiny/data/sabah_200.shp /home/shiny/data/size4.tif /home/shiny/data/out_lcc_scenarioV.tif 100000 2 100 1 &> /home/shiny/data/log2COLA_lcc_scenarioV.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/lcc.py /home/shiny/data/sabah_50.shp /home/shiny/data/size4.tif /home/shiny/data/out_lcc_scenarioW.tif 100000 2 100 1 &> /home/shiny/data/log2COLA_lcc_scenarioW.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/lcc.py /home/shiny/data/sabah_500.shp /home/shiny/data/size4.tif /home/shiny/data/out_lcc_scenarioX.tif 100000 2 100 1 &> /home/shiny/data/log2COLA_lcc_scenarioX.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/lcc.py /home/shiny/data/sabah_10.shp /home/shiny/data/size5.tif /home/shiny/data/out_lcc_scenarioY.tif 100000 2 100 1 &> /home/shiny/data/log2COLA_lcc_scenarioY.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/lcc.py /home/shiny/data/sabah_100.shp /home/shiny/data/size5.tif /home/shiny/data/out_lcc_scenarioZ.tif 100000 2 100 1 &> /home/shiny/data/log2COLA_lcc_scenarioZ.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/lcc.py /home/shiny/data/sabah_20.shp /home/shiny/data/size5.tif /home/shiny/data/out_lcc_scenarioAA.tif 100000 2 100 1 &> /home/shiny/data/log2COLA_lcc_scenarioAA.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/lcc.py /home/shiny/data/sabah_200.shp /home/shiny/data/size5.tif /home/shiny/data/out_lcc_scenarioAB.tif 100000 2 100 1 &> /home/shiny/data/log2COLA_lcc_scenarioAB.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/lcc.py /home/shiny/data/sabah_50.shp /home/shiny/data/size5.tif /home/shiny/data/out_lcc_scenarioAC.tif 100000 2 100 1 &> /home/shiny/data/log2COLA_lcc_scenarioAC.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/lcc.py /home/shiny/data/sabah_500.shp /home/shiny/data/size5.tif /home/shiny/data/out_lcc_scenarioAD.tif 100000 2 100 1 &> /home/shiny/data/log2COLA_lcc_scenarioAD.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/lcc.py /home/shiny/data/sabah_10.shp /home/shiny/data/size6.tif /home/shiny/data/out_lcc_scenarioAE.tif 100000 2 100 1 &> /home/shiny/data/log2COLA_lcc_scenarioAE.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/lcc.py /home/shiny/data/sabah_100.shp /home/shiny/data/size6.tif /home/shiny/data/out_lcc_scenarioAF.tif 100000 2 100 1 &> /home/shiny/data/log2COLA_lcc_scenarioAF.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/lcc.py /home/shiny/data/sabah_20.shp /home/shiny/data/size6.tif /home/shiny/data/out_lcc_scenarioAG.tif 100000 2 100 1 &> /home/shiny/data/log2COLA_lcc_scenarioAG.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/lcc.py /home/shiny/data/sabah_200.shp /home/shiny/data/size6.tif /home/shiny/data/out_lcc_scenarioAH.tif 100000 2 100 1 &> /home/shiny/data/log2COLA_lcc_scenarioAH.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/lcc.py /home/shiny/data/sabah_50.shp /home/shiny/data/size6.tif /home/shiny/data/out_lcc_scenarioAI.tif 100000 2 100 1 &> /home/shiny/data/log2COLA_lcc_scenarioAI.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/lcc.py /home/shiny/data/sabah_500.shp /home/shiny/data/size6.tif /home/shiny/data/out_lcc_scenarioAJ.tif 100000 2 100 1 &> /home/shiny/data/log2COLA_lcc_scenarioAJ.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/lcc.py /home/shiny/data/sabah_10.shp /home/shiny/data/size7.tif /home/shiny/data/out_lcc_scenarioAK.tif 100000 2 100 1 &> /home/shiny/data/log2COLA_lcc_scenarioAK.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/lcc.py /home/shiny/data/sabah_100.shp /home/shiny/data/size7.tif /home/shiny/data/out_lcc_scenarioAL.tif 100000 2 100 1 &> /home/shiny/data/log2COLA_lcc_scenarioAL.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/lcc.py /home/shiny/data/sabah_20.shp /home/shiny/data/size7.tif /home/shiny/data/out_lcc_scenarioAM.tif 100000 2 100 1 &> /home/shiny/data/log2COLA_lcc_scenarioAM.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/lcc.py /home/shiny/data/sabah_200.shp /home/shiny/data/size7.tif /home/shiny/data/out_lcc_scenarioAN.tif 100000 2 100 1 &> /home/shiny/data/log2COLA_lcc_scenarioAN.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/lcc.py /home/shiny/data/sabah_50.shp /home/shiny/data/size7.tif /home/shiny/data/out_lcc_scenarioAO.tif 100000 2 100 1 &> /home/shiny/data/log2COLA_lcc_scenarioAO.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/lcc.py /home/shiny/data/sabah_500.shp /home/shiny/data/size7.tif /home/shiny/data/out_lcc_scenarioAP.tif 100000 2 100 1 &> /home/shiny/data/log2COLA_lcc_scenarioAP.txt

taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py crk_scenarioA.rip &> /home/shiny/data/log2UNIC_crk_scenarioA.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py crk_scenarioB.rip &> /home/shiny/data/log2UNIC_crk_scenarioB.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py crk_scenarioC.rip &> /home/shiny/data/log2UNIC_crk_scenarioC.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py crk_scenarioD.rip &> /home/shiny/data/log2UNIC_crk_scenarioD.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py crk_scenarioE.rip &> /home/shiny/data/log2UNIC_crk_scenarioE.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py crk_scenarioF.rip &> /home/shiny/data/log2UNIC_crk_scenarioF.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py crk_scenarioG.rip &> /home/shiny/data/log2UNIC_crk_scenarioG.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py crk_scenarioH.rip &> /home/shiny/data/log2UNIC_crk_scenarioH.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py crk_scenarioI.rip &> /home/shiny/data/log2UNIC_crk_scenarioI.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py crk_scenarioJ.rip &> /home/shiny/data/log2UNIC_crk_scenarioJ.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py crk_scenarioK.rip &> /home/shiny/data/log2UNIC_crk_scenarioK.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py crk_scenarioL.rip &> /home/shiny/data/log2UNIC_crk_scenarioL.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py crk_scenarioM.rip &> /home/shiny/data/log2UNIC_crk_scenarioM.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py crk_scenarioN.rip &> /home/shiny/data/log2UNIC_crk_scenarioN.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py crk_scenarioO.rip &> /home/shiny/data/log2UNIC_crk_scenarioO.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py crk_scenarioP.rip &> /home/shiny/data/log2UNIC_crk_scenarioP.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py crk_scenarioQ.rip &> /home/shiny/data/log2UNIC_crk_scenarioQ.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py crk_scenarioR.rip &> /home/shiny/data/log2UNIC_crk_scenarioR.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py crk_scenarioS.rip &> /home/shiny/data/log2UNIC_crk_scenarioS.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py crk_scenarioT.rip &> /home/shiny/data/log2UNIC_crk_scenarioT.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py crk_scenarioU.rip &> /home/shiny/data/log2UNIC_crk_scenarioU.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py crk_scenarioV.rip &> /home/shiny/data/log2UNIC_crk_scenarioV.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py crk_scenarioW.rip &> /home/shiny/data/log2UNIC_crk_scenarioW.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py crk_scenarioX.rip &> /home/shiny/data/log2UNIC_crk_scenarioX.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py crk_scenarioY.rip &> /home/shiny/data/log2UNIC_crk_scenarioY.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py crk_scenarioZ.rip &> /home/shiny/data/log2UNIC_crk_scenarioZ.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py crk_scenarioAA.rip &> /home/shiny/data/log2UNIC_crk_scenarioAA.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py crk_scenarioAB.rip &> /home/shiny/data/log2UNIC_crk_scenarioAB.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py crk_scenarioAC.rip &> /home/shiny/data/log2UNIC_crk_scenarioAC.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py crk_scenarioAD.rip &> /home/shiny/data/log2UNIC_crk_scenarioAD.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py crk_scenarioAE.rip &> /home/shiny/data/log2UNIC_crk_scenarioAE.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py crk_scenarioAF.rip &> /home/shiny/data/log2UNIC_crk_scenarioAF.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py crk_scenarioAG.rip &> /home/shiny/data/log2UNIC_crk_scenarioAG.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py crk_scenarioAH.rip &> /home/shiny/data/log2UNIC_crk_scenarioAH.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py crk_scenarioAI.rip &> /home/shiny/data/log2UNIC_crk_scenarioAI.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py crk_scenarioAJ.rip &> /home/shiny/data/log2UNIC_crk_scenarioAJ.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py crk_scenarioAK.rip &> /home/shiny/data/log2UNIC_crk_scenarioAK.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py crk_scenarioAL.rip &> /home/shiny/data/log2UNIC_crk_scenarioAL.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py crk_scenarioAM.rip &> /home/shiny/data/log2UNIC_crk_scenarioAM.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py crk_scenarioAN.rip &> /home/shiny/data/log2UNIC_crk_scenarioAN.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py crk_scenarioAO.rip &> /home/shiny/data/log2UNIC_crk_scenarioAO.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py crk_scenarioAP.rip &> /home/shiny/data/log2UNIC_crk_scenarioAP.txt

taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/crk.py /home/shiny/data/sabah_10.shp /home/shiny/data/size1.tif /home/shiny/data/out_crk_scenarioA.tif 1000000 linear 10000 1 &> /home/shiny/data/log2COLA_crk_scenarioA.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/crk.py /home/shiny/data/sabah_100.shp /home/shiny/data/size1.tif /home/shiny/data/out_crk_scenarioB.tif 1000000 linear 10000 1 &> /home/shiny/data/log2COLA_crk_scenarioB.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/crk.py /home/shiny/data/sabah_20.shp /home/shiny/data/size1.tif /home/shiny/data/out_crk_scenarioC.tif 1000000 linear 10000 1 &> /home/shiny/data/log2COLA_crk_scenarioC.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/crk.py /home/shiny/data/sabah_200.shp /home/shiny/data/size1.tif /home/shiny/data/out_crk_scenarioD.tif 1000000 linear 10000 1 &> /home/shiny/data/log2COLA_crk_scenarioD.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/crk.py /home/shiny/data/sabah_50.shp /home/shiny/data/size1.tif /home/shiny/data/out_crk_scenarioE.tif 1000000 linear 10000 1 &> /home/shiny/data/log2COLA_crk_scenarioE.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/crk.py /home/shiny/data/sabah_500.shp /home/shiny/data/size1.tif /home/shiny/data/out_crk_scenarioF.tif 1000000 linear 10000 1 &> /home/shiny/data/log2COLA_crk_scenarioF.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/crk.py /home/shiny/data/sabah_10.shp /home/shiny/data/size2.tif /home/shiny/data/out_crk_scenarioG.tif 1000000 linear 10000 1 &> /home/shiny/data/log2COLA_crk_scenarioG.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/crk.py /home/shiny/data/sabah_100.shp /home/shiny/data/size2.tif /home/shiny/data/out_crk_scenarioH.tif 1000000 linear 10000 1 &> /home/shiny/data/log2COLA_crk_scenarioH.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/crk.py /home/shiny/data/sabah_20.shp /home/shiny/data/size2.tif /home/shiny/data/out_crk_scenarioI.tif 1000000 linear 10000 1 &> /home/shiny/data/log2COLA_crk_scenarioI.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/crk.py /home/shiny/data/sabah_200.shp /home/shiny/data/size2.tif /home/shiny/data/out_crk_scenarioJ.tif 1000000 linear 10000 1 &> /home/shiny/data/log2COLA_crk_scenarioJ.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/crk.py /home/shiny/data/sabah_50.shp /home/shiny/data/size2.tif /home/shiny/data/out_crk_scenarioK.tif 1000000 linear 10000 1 &> /home/shiny/data/log2COLA_crk_scenarioK.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/crk.py /home/shiny/data/sabah_500.shp /home/shiny/data/size2.tif /home/shiny/data/out_crk_scenarioL.tif 1000000 linear 10000 1 &> /home/shiny/data/log2COLA_crk_scenarioL.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/crk.py /home/shiny/data/sabah_10.shp /home/shiny/data/size3.tif /home/shiny/data/out_crk_scenarioM.tif 1000000 linear 10000 1 &> /home/shiny/data/log2COLA_crk_scenarioM.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/crk.py /home/shiny/data/sabah_100.shp /home/shiny/data/size3.tif /home/shiny/data/out_crk_scenarioN.tif 1000000 linear 10000 1 &> /home/shiny/data/log2COLA_crk_scenarioN.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/crk.py /home/shiny/data/sabah_20.shp /home/shiny/data/size3.tif /home/shiny/data/out_crk_scenarioO.tif 1000000 linear 10000 1 &> /home/shiny/data/log2COLA_crk_scenarioO.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/crk.py /home/shiny/data/sabah_200.shp /home/shiny/data/size3.tif /home/shiny/data/out_crk_scenarioP.tif 1000000 linear 10000 1 &> /home/shiny/data/log2COLA_crk_scenarioP.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/crk.py /home/shiny/data/sabah_50.shp /home/shiny/data/size3.tif /home/shiny/data/out_crk_scenarioQ.tif 1000000 linear 10000 1 &> /home/shiny/data/log2COLA_crk_scenarioQ.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/crk.py /home/shiny/data/sabah_500.shp /home/shiny/data/size3.tif /home/shiny/data/out_crk_scenarioR.tif 1000000 linear 10000 1 &> /home/shiny/data/log2COLA_crk_scenarioR.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/crk.py /home/shiny/data/sabah_10.shp /home/shiny/data/size4.tif /home/shiny/data/out_crk_scenarioS.tif 1000000 linear 10000 1 &> /home/shiny/data/log2COLA_crk_scenarioS.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/crk.py /home/shiny/data/sabah_100.shp /home/shiny/data/size4.tif /home/shiny/data/out_crk_scenarioT.tif 1000000 linear 10000 1 &> /home/shiny/data/log2COLA_crk_scenarioT.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/crk.py /home/shiny/data/sabah_20.shp /home/shiny/data/size4.tif /home/shiny/data/out_crk_scenarioU.tif 1000000 linear 10000 1 &> /home/shiny/data/log2COLA_crk_scenarioU.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/crk.py /home/shiny/data/sabah_200.shp /home/shiny/data/size4.tif /home/shiny/data/out_crk_scenarioV.tif 1000000 linear 10000 1 &> /home/shiny/data/log2COLA_crk_scenarioV.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/crk.py /home/shiny/data/sabah_50.shp /home/shiny/data/size4.tif /home/shiny/data/out_crk_scenarioW.tif 1000000 linear 10000 1 &> /home/shiny/data/log2COLA_crk_scenarioW.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/crk.py /home/shiny/data/sabah_500.shp /home/shiny/data/size4.tif /home/shiny/data/out_crk_scenarioX.tif 1000000 linear 10000 1 &> /home/shiny/data/log2COLA_crk_scenarioX.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/crk.py /home/shiny/data/sabah_10.shp /home/shiny/data/size5.tif /home/shiny/data/out_crk_scenarioY.tif 1000000 linear 10000 1 &> /home/shiny/data/log2COLA_crk_scenarioY.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/crk.py /home/shiny/data/sabah_100.shp /home/shiny/data/size5.tif /home/shiny/data/out_crk_scenarioZ.tif 1000000 linear 10000 1 &> /home/shiny/data/log2COLA_crk_scenarioZ.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/crk.py /home/shiny/data/sabah_20.shp /home/shiny/data/size5.tif /home/shiny/data/out_crk_scenarioAA.tif 1000000 linear 10000 1 &> /home/shiny/data/log2COLA_crk_scenarioAA.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/crk.py /home/shiny/data/sabah_200.shp /home/shiny/data/size5.tif /home/shiny/data/out_crk_scenarioAB.tif 1000000 linear 10000 1 &> /home/shiny/data/log2COLA_crk_scenarioAB.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/crk.py /home/shiny/data/sabah_50.shp /home/shiny/data/size5.tif /home/shiny/data/out_crk_scenarioAC.tif 1000000 linear 10000 1 &> /home/shiny/data/log2COLA_crk_scenarioAC.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/crk.py /home/shiny/data/sabah_500.shp /home/shiny/data/size5.tif /home/shiny/data/out_crk_scenarioAD.tif 1000000 linear 10000 1 &> /home/shiny/data/log2COLA_crk_scenarioAD.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/crk.py /home/shiny/data/sabah_10.shp /home/shiny/data/size6.tif /home/shiny/data/out_crk_scenarioAE.tif 1000000 linear 10000 1 &> /home/shiny/data/log2COLA_crk_scenarioAE.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/crk.py /home/shiny/data/sabah_100.shp /home/shiny/data/size6.tif /home/shiny/data/out_crk_scenarioAF.tif 1000000 linear 10000 1 &> /home/shiny/data/log2COLA_crk_scenarioAF.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/crk.py /home/shiny/data/sabah_20.shp /home/shiny/data/size6.tif /home/shiny/data/out_crk_scenarioAG.tif 1000000 linear 10000 1 &> /home/shiny/data/log2COLA_crk_scenarioAG.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/crk.py /home/shiny/data/sabah_200.shp /home/shiny/data/size6.tif /home/shiny/data/out_crk_scenarioAH.tif 1000000 linear 10000 1 &> /home/shiny/data/log2COLA_crk_scenarioAH.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/crk.py /home/shiny/data/sabah_50.shp /home/shiny/data/size6.tif /home/shiny/data/out_crk_scenarioAI.tif 1000000 linear 10000 1 &> /home/shiny/data/log2COLA_crk_scenarioAI.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/crk.py /home/shiny/data/sabah_500.shp /home/shiny/data/size6.tif /home/shiny/data/out_crk_scenarioAJ.tif 1000000 linear 10000 1 &> /home/shiny/data/log2COLA_crk_scenarioAJ.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/crk.py /home/shiny/data/sabah_10.shp /home/shiny/data/size7.tif /home/shiny/data/out_crk_scenarioAK.tif 1000000 linear 10000 1 &> /home/shiny/data/log2COLA_crk_scenarioAK.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/crk.py /home/shiny/data/sabah_100.shp /home/shiny/data/size7.tif /home/shiny/data/out_crk_scenarioAL.tif 1000000 linear 10000 1 &> /home/shiny/data/log2COLA_crk_scenarioAL.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/crk.py /home/shiny/data/sabah_20.shp /home/shiny/data/size7.tif /home/shiny/data/out_crk_scenarioAM.tif 1000000 linear 10000 1 &> /home/shiny/data/log2COLA_crk_scenarioAM.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/crk.py /home/shiny/data/sabah_200.shp /home/shiny/data/size7.tif /home/shiny/data/out_crk_scenarioAN.tif 1000000 linear 10000 1 &> /home/shiny/data/log2COLA_crk_scenarioAN.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/crk.py /home/shiny/data/sabah_50.shp /home/shiny/data/size7.tif /home/shiny/data/out_crk_scenarioAO.tif 1000000 linear 10000 1 &> /home/shiny/data/log2COLA_crk_scenarioAO.txt
#taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/crk.py /home/shiny/data/sabah_500.shp /home/shiny/data/size7.tif /home/shiny/data/out_crk_scenarioAP.tif 1000000 linear 10000 1 &> /home/shiny/data/log2COLA_crk_scenarioAP.txt

taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py mat_scenarioA.rip &> /home/shiny/data/log2UNIC_mat_scenarioA.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py mat_scenarioB.rip &> /home/shiny/data/log2UNIC_mat_scenarioB.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py mat_scenarioC.rip &> /home/shiny/data/log2UNIC_mat_scenarioC.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py mat_scenarioD.rip &> /home/shiny/data/log2UNIC_mat_scenarioD.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py mat_scenarioE.rip &> /home/shiny/data/log2UNIC_mat_scenarioE.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py mat_scenarioF.rip &> /home/shiny/data/log2UNIC_mat_scenarioF.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py mat_scenarioG.rip &> /home/shiny/data/log2UNIC_mat_scenarioG.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py mat_scenarioH.rip &> /home/shiny/data/log2UNIC_mat_scenarioH.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py mat_scenarioI.rip &> /home/shiny/data/log2UNIC_mat_scenarioI.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py mat_scenarioJ.rip &> /home/shiny/data/log2UNIC_mat_scenarioJ.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py mat_scenarioK.rip &> /home/shiny/data/log2UNIC_mat_scenarioK.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py mat_scenarioL.rip &> /home/shiny/data/log2UNIC_mat_scenarioL.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py mat_scenarioM.rip &> /home/shiny/data/log2UNIC_mat_scenarioM.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py mat_scenarioN.rip &> /home/shiny/data/log2UNIC_mat_scenarioN.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py mat_scenarioO.rip &> /home/shiny/data/log2UNIC_mat_scenarioO.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py mat_scenarioP.rip &> /home/shiny/data/log2UNIC_mat_scenarioP.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py mat_scenarioQ.rip &> /home/shiny/data/log2UNIC_mat_scenarioQ.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py mat_scenarioR.rip &> /home/shiny/data/log2UNIC_mat_scenarioR.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py mat_scenarioS.rip &> /home/shiny/data/log2UNIC_mat_scenarioS.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py mat_scenarioT.rip &> /home/shiny/data/log2UNIC_mat_scenarioT.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py mat_scenarioU.rip &> /home/shiny/data/log2UNIC_mat_scenarioU.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py mat_scenarioV.rip &> /home/shiny/data/log2UNIC_mat_scenarioV.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py mat_scenarioW.rip &> /home/shiny/data/log2UNIC_mat_scenarioW.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py mat_scenarioX.rip &> /home/shiny/data/log2UNIC_mat_scenarioX.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py mat_scenarioY.rip &> /home/shiny/data/log2UNIC_mat_scenarioY.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py mat_scenarioZ.rip &> /home/shiny/data/log2UNIC_mat_scenarioZ.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py mat_scenarioAA.rip &> /home/shiny/data/log2UNIC_mat_scenarioAA.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py mat_scenarioAB.rip &> /home/shiny/data/log2UNIC_mat_scenarioAB.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py mat_scenarioAC.rip &> /home/shiny/data/log2UNIC_mat_scenarioAC.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py mat_scenarioAD.rip &> /home/shiny/data/log2UNIC_mat_scenarioAD.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py mat_scenarioAE.rip &> /home/shiny/data/log2UNIC_mat_scenarioAE.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py mat_scenarioAF.rip &> /home/shiny/data/log2UNIC_mat_scenarioAF.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py mat_scenarioAG.rip &> /home/shiny/data/log2UNIC_mat_scenarioAG.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py mat_scenarioAH.rip &> /home/shiny/data/log2UNIC_mat_scenarioAH.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py mat_scenarioAI.rip &> /home/shiny/data/log2UNIC_mat_scenarioAI.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py mat_scenarioAJ.rip &> /home/shiny/data/log2UNIC_mat_scenarioAJ.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py mat_scenarioAK.rip &> /home/shiny/data/log2UNIC_mat_scenarioAK.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py mat_scenarioAL.rip &> /home/shiny/data/log2UNIC_mat_scenarioAL.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py mat_scenarioAM.rip &> /home/shiny/data/log2UNIC_mat_scenarioAM.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py mat_scenarioAN.rip &> /home/shiny/data/log2UNIC_mat_scenarioAN.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py mat_scenarioAO.rip &> /home/shiny/data/log2UNIC_mat_scenarioAO.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py mat_scenarioAP.rip &> /home/shiny/data/log2UNIC_mat_scenarioAP.txt

taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/create_cdmat.py /home/shiny/data/sabah_10.shp /home/shiny/data/size1.tif /home/shiny/data/out_mat_scenarioA.csv 100000 1 &> /home/shiny/data/log2COLA_mat_scenarioA.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/create_cdmat.py /home/shiny/data/sabah_100.shp /home/shiny/data/size1.tif /home/shiny/data/out_mat_scenarioB.csv 100000 1 &> /home/shiny/data/log2COLA_mat_scenarioB.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/create_cdmat.py /home/shiny/data/sabah_20.shp /home/shiny/data/size1.tif /home/shiny/data/out_mat_scenarioC.csv 100000 1 &> /home/shiny/data/log2COLA_mat_scenarioC.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/create_cdmat.py /home/shiny/data/sabah_200.shp /home/shiny/data/size1.tif /home/shiny/data/out_mat_scenarioD.csv 100000 1 &> /home/shiny/data/log2COLA_mat_scenarioD.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/create_cdmat.py /home/shiny/data/sabah_50.shp /home/shiny/data/size1.tif /home/shiny/data/out_mat_scenarioE.csv 100000 1 &> /home/shiny/data/log2COLA_mat_scenarioE.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/create_cdmat.py /home/shiny/data/sabah_500.shp /home/shiny/data/size1.tif /home/shiny/data/out_mat_scenarioF.csv 100000 1 &> /home/shiny/data/log2COLA_mat_scenarioF.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/create_cdmat.py /home/shiny/data/sabah_10.shp /home/shiny/data/size2.tif /home/shiny/data/out_mat_scenarioG.csv 100000 1 &> /home/shiny/data/log2COLA_mat_scenarioG.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/create_cdmat.py /home/shiny/data/sabah_100.shp /home/shiny/data/size2.tif /home/shiny/data/out_mat_scenarioH.csv 100000 1 &> /home/shiny/data/log2COLA_mat_scenarioH.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/create_cdmat.py /home/shiny/data/sabah_20.shp /home/shiny/data/size2.tif /home/shiny/data/out_mat_scenarioI.csv 100000 1 &> /home/shiny/data/log2COLA_mat_scenarioI.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/create_cdmat.py /home/shiny/data/sabah_200.shp /home/shiny/data/size2.tif /home/shiny/data/out_mat_scenarioJ.csv 100000 1 &> /home/shiny/data/log2COLA_mat_scenarioJ.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/create_cdmat.py /home/shiny/data/sabah_50.shp /home/shiny/data/size2.tif /home/shiny/data/out_mat_scenarioK.csv 100000 1 &> /home/shiny/data/log2COLA_mat_scenarioK.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/create_cdmat.py /home/shiny/data/sabah_500.shp /home/shiny/data/size2.tif /home/shiny/data/out_mat_scenarioL.csv 100000 1 &> /home/shiny/data/log2COLA_mat_scenarioL.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/create_cdmat.py /home/shiny/data/sabah_10.shp /home/shiny/data/size3.tif /home/shiny/data/out_mat_scenarioM.csv 100000 1 &> /home/shiny/data/log2COLA_mat_scenarioM.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/create_cdmat.py /home/shiny/data/sabah_100.shp /home/shiny/data/size3.tif /home/shiny/data/out_mat_scenarioN.csv 100000 1 &> /home/shiny/data/log2COLA_mat_scenarioN.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/create_cdmat.py /home/shiny/data/sabah_20.shp /home/shiny/data/size3.tif /home/shiny/data/out_mat_scenarioO.csv 100000 1 &> /home/shiny/data/log2COLA_mat_scenarioO.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/create_cdmat.py /home/shiny/data/sabah_200.shp /home/shiny/data/size3.tif /home/shiny/data/out_mat_scenarioP.csv 100000 1 &> /home/shiny/data/log2COLA_mat_scenarioP.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/create_cdmat.py /home/shiny/data/sabah_50.shp /home/shiny/data/size3.tif /home/shiny/data/out_mat_scenarioQ.csv 100000 1 &> /home/shiny/data/log2COLA_mat_scenarioQ.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/create_cdmat.py /home/shiny/data/sabah_500.shp /home/shiny/data/size3.tif /home/shiny/data/out_mat_scenarioR.csv 100000 1 &> /home/shiny/data/log2COLA_mat_scenarioR.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/create_cdmat.py /home/shiny/data/sabah_10.shp /home/shiny/data/size4.tif /home/shiny/data/out_mat_scenarioS.csv 100000 1 &> /home/shiny/data/log2COLA_mat_scenarioS.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/create_cdmat.py /home/shiny/data/sabah_100.shp /home/shiny/data/size4.tif /home/shiny/data/out_mat_scenarioT.csv 100000 1 &> /home/shiny/data/log2COLA_mat_scenarioT.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/create_cdmat.py /home/shiny/data/sabah_20.shp /home/shiny/data/size4.tif /home/shiny/data/out_mat_scenarioU.csv 100000 1 &> /home/shiny/data/log2COLA_mat_scenarioU.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/create_cdmat.py /home/shiny/data/sabah_200.shp /home/shiny/data/size4.tif /home/shiny/data/out_mat_scenarioV.csv 100000 1 &> /home/shiny/data/log2COLA_mat_scenarioV.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/create_cdmat.py /home/shiny/data/sabah_50.shp /home/shiny/data/size4.tif /home/shiny/data/out_mat_scenarioW.csv 100000 1 &> /home/shiny/data/log2COLA_mat_scenarioW.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/create_cdmat.py /home/shiny/data/sabah_500.shp /home/shiny/data/size4.tif /home/shiny/data/out_mat_scenarioX.csv 100000 1 &> /home/shiny/data/log2COLA_mat_scenarioX.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/create_cdmat.py /home/shiny/data/sabah_10.shp /home/shiny/data/size5.tif /home/shiny/data/out_mat_scenarioY.csv 100000 1 &> /home/shiny/data/log2COLA_mat_scenarioY.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/create_cdmat.py /home/shiny/data/sabah_100.shp /home/shiny/data/size5.tif /home/shiny/data/out_mat_scenarioZ.csv 100000 1 &> /home/shiny/data/log2COLA_mat_scenarioZ.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/create_cdmat.py /home/shiny/data/sabah_20.shp /home/shiny/data/size5.tif /home/shiny/data/out_mat_scenarioAA.csv 100000 1 &> /home/shiny/data/log2COLA_mat_scenarioAA.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/create_cdmat.py /home/shiny/data/sabah_200.shp /home/shiny/data/size5.tif /home/shiny/data/out_mat_scenarioAB.csv 100000 1 &> /home/shiny/data/log2COLA_mat_scenarioAB.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/create_cdmat.py /home/shiny/data/sabah_50.shp /home/shiny/data/size5.tif /home/shiny/data/out_mat_scenarioAC.csv 100000 1 &> /home/shiny/data/log2COLA_mat_scenarioAC.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/create_cdmat.py /home/shiny/data/sabah_500.shp /home/shiny/data/size5.tif /home/shiny/data/out_mat_scenarioAD.csv 100000 1 &> /home/shiny/data/log2COLA_mat_scenarioAD.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/create_cdmat.py /home/shiny/data/sabah_10.shp /home/shiny/data/size6.tif /home/shiny/data/out_mat_scenarioAE.csv 100000 1 &> /home/shiny/data/log2COLA_mat_scenarioAE.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/create_cdmat.py /home/shiny/data/sabah_100.shp /home/shiny/data/size6.tif /home/shiny/data/out_mat_scenarioAF.csv 100000 1 &> /home/shiny/data/log2COLA_mat_scenarioAF.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/create_cdmat.py /home/shiny/data/sabah_20.shp /home/shiny/data/size6.tif /home/shiny/data/out_mat_scenarioAG.csv 100000 1 &> /home/shiny/data/log2COLA_mat_scenarioAG.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/create_cdmat.py /home/shiny/data/sabah_200.shp /home/shiny/data/size6.tif /home/shiny/data/out_mat_scenarioAH.csv 100000 1 &> /home/shiny/data/log2COLA_mat_scenarioAH.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/create_cdmat.py /home/shiny/data/sabah_50.shp /home/shiny/data/size6.tif /home/shiny/data/out_mat_scenarioAI.csv 100000 1 &> /home/shiny/data/log2COLA_mat_scenarioAI.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/create_cdmat.py /home/shiny/data/sabah_500.shp /home/shiny/data/size6.tif /home/shiny/data/out_mat_scenarioAJ.csv 100000 1 &> /home/shiny/data/log2COLA_mat_scenarioAJ.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/create_cdmat.py /home/shiny/data/sabah_10.shp /home/shiny/data/size7.tif /home/shiny/data/out_mat_scenarioAK.csv 100000 1 &> /home/shiny/data/log2COLA_mat_scenarioAK.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/create_cdmat.py /home/shiny/data/sabah_100.shp /home/shiny/data/size7.tif /home/shiny/data/out_mat_scenarioAL.csv 100000 1 &> /home/shiny/data/log2COLA_mat_scenarioAL.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/create_cdmat.py /home/shiny/data/sabah_20.shp /home/shiny/data/size7.tif /home/shiny/data/out_mat_scenarioAM.csv 100000 1 &> /home/shiny/data/log2COLA_mat_scenarioAM.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/create_cdmat.py /home/shiny/data/sabah_200.shp /home/shiny/data/size7.tif /home/shiny/data/out_mat_scenarioAN.csv 100000 1 &> /home/shiny/data/log2COLA_mat_scenarioAN.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/create_cdmat.py /home/shiny/data/sabah_50.shp /home/shiny/data/size7.tif /home/shiny/data/out_mat_scenarioAO.csv 100000 1 &> /home/shiny/data/log2COLA_mat_scenarioAO.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/create_cdmat.py /home/shiny/data/sabah_500.shp /home/shiny/data/size7.tif /home/shiny/data/out_mat_scenarioAP.csv 100000 1 &> /home/shiny/data/log2COLA_mat_scenarioAP.txt
