### chmod +x /home/shiny/connectscape/bash_iteration2b.sh    ## Run: /home/shiny/connectscape/bash_iteration2b.sh &
 ## /home/shiny/connectscape/bash_iteration2b.sh & 
cd /home/shiny/UNICOR/unicor/

taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py crk_scenarioAD.rip &> /home/shiny/data/log2UNIC_crk_scenarioAD.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py crk_scenarioF.rip &> /home/shiny/data/log2UNIC_crk_scenarioF.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py mat_scenarioZ.rip &> /home/shiny/data/log2UNIC_mat_scenarioZ.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py mat_scenarioV.rip &> /home/shiny/data/log2UNIC_mat_scenarioV.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py crk_scenarioAE.rip &> /home/shiny/data/log2UNIC_crk_scenarioAE.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py crk_scenarioW.rip &> /home/shiny/data/log2UNIC_crk_scenarioW.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py mat_scenarioAI.rip &> /home/shiny/data/log2UNIC_mat_scenarioAI.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py mat_scenarioAM.rip &> /home/shiny/data/log2UNIC_mat_scenarioAM.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py mat_scenarioAD.rip &> /home/shiny/data/log2UNIC_mat_scenarioAD.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py crk_scenarioAC.rip &> /home/shiny/data/log2UNIC_crk_scenarioAC.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py crk_scenarioAA.rip &> /home/shiny/data/log2UNIC_crk_scenarioAA.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py lcc_scenarioAF.rip &> /home/shiny/data/log2UNIC_lcc_scenarioAF.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py mat_scenarioAB.rip &> /home/shiny/data/log2UNIC_mat_scenarioAB.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py crk_scenarioC.rip &> /home/shiny/data/log2UNIC_crk_scenarioC.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python /home/shiny/connecting-landscapes/src/create_cdmat.py /home/shiny/data/sabah_500.shp /home/shiny/data/size7.tif /home/shiny/data/out_mat_scenarioAP.csv 100000 1 &> /home/shiny/data/log2COLA_mat_scenarioAP.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py mat_scenarioAE.rip &> /home/shiny/data/log2UNIC_mat_scenarioAE.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py crk_scenarioP.rip &> /home/shiny/data/log2UNIC_crk_scenarioP.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py lcc_scenarioAP.rip &> /home/shiny/data/log2UNIC_lcc_scenarioAP.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py lcc_scenarioAN.rip &> /home/shiny/data/log2UNIC_lcc_scenarioAN.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py crk_scenarioL.rip &> /home/shiny/data/log2UNIC_crk_scenarioL.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py lcc_scenarioAJ.rip &> /home/shiny/data/log2UNIC_lcc_scenarioAJ.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py mat_scenarioM.rip &> /home/shiny/data/log2UNIC_mat_scenarioM.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py mat_scenarioAA.rip &> /home/shiny/data/log2UNIC_mat_scenarioAA.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py mat_scenarioR.rip &> /home/shiny/data/log2UNIC_mat_scenarioR.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py crk_scenarioQ.rip &> /home/shiny/data/log2UNIC_crk_scenarioQ.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py crk_scenarioAL.rip &> /home/shiny/data/log2UNIC_crk_scenarioAL.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py crk_scenarioH.rip &> /home/shiny/data/log2UNIC_crk_scenarioH.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py mat_scenarioAC.rip &> /home/shiny/data/log2UNIC_mat_scenarioAC.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py mat_scenarioAH.rip &> /home/shiny/data/log2UNIC_mat_scenarioAH.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py crk_scenarioR.rip &> /home/shiny/data/log2UNIC_crk_scenarioR.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py crk_scenarioAB.rip &> /home/shiny/data/log2UNIC_crk_scenarioAB.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py mat_scenarioAO.rip &> /home/shiny/data/log2UNIC_mat_scenarioAO.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py mat_scenarioAP.rip &> /home/shiny/data/log2UNIC_mat_scenarioAP.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py crk_scenarioAK.rip &> /home/shiny/data/log2UNIC_crk_scenarioAK.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py mat_scenarioT.rip &> /home/shiny/data/log2UNIC_mat_scenarioT.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py mat_scenarioAG.rip &> /home/shiny/data/log2UNIC_mat_scenarioAG.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py crk_scenarioI.rip &> /home/shiny/data/log2UNIC_crk_scenarioI.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py crk_scenarioAJ.rip &> /home/shiny/data/log2UNIC_crk_scenarioAJ.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py mat_scenarioA.rip &> /home/shiny/data/log2UNIC_mat_scenarioA.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py crk_scenarioB.rip &> /home/shiny/data/log2UNIC_crk_scenarioB.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py lcc_scenarioAI.rip &> /home/shiny/data/log2UNIC_lcc_scenarioAI.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py lcc_scenarioAH.rip &> /home/shiny/data/log2UNIC_lcc_scenarioAH.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py mat_scenarioH.rip &> /home/shiny/data/log2UNIC_mat_scenarioH.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py crk_scenarioAP.rip &> /home/shiny/data/log2UNIC_crk_scenarioAP.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py crk_scenarioAN.rip &> /home/shiny/data/log2UNIC_crk_scenarioAN.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py mat_scenarioN.rip &> /home/shiny/data/log2UNIC_mat_scenarioN.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py crk_scenarioD.rip &> /home/shiny/data/log2UNIC_crk_scenarioD.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py crk_scenarioJ.rip &> /home/shiny/data/log2UNIC_crk_scenarioJ.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py mat_scenarioW.rip &> /home/shiny/data/log2UNIC_mat_scenarioW.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py lcc_scenarioAE.rip &> /home/shiny/data/log2UNIC_lcc_scenarioAE.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py mat_scenarioS.rip &> /home/shiny/data/log2UNIC_mat_scenarioS.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py mat_scenarioB.rip &> /home/shiny/data/log2UNIC_mat_scenarioB.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py crk_scenarioAG.rip &> /home/shiny/data/log2UNIC_crk_scenarioAG.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py crk_scenarioAI.rip &> /home/shiny/data/log2UNIC_crk_scenarioAI.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py mat_scenarioAF.rip &> /home/shiny/data/log2UNIC_mat_scenarioAF.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py crk_scenarioAM.rip &> /home/shiny/data/log2UNIC_crk_scenarioAM.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py mat_scenarioAN.rip &> /home/shiny/data/log2UNIC_mat_scenarioAN.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py crk_scenarioAH.rip &> /home/shiny/data/log2UNIC_crk_scenarioAH.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py mat_scenarioO.rip &> /home/shiny/data/log2UNIC_mat_scenarioO.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py mat_scenarioG.rip &> /home/shiny/data/log2UNIC_mat_scenarioG.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py mat_scenarioAK.rip &> /home/shiny/data/log2UNIC_mat_scenarioAK.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py crk_scenarioA.rip &> /home/shiny/data/log2UNIC_crk_scenarioA.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py crk_scenarioU.rip &> /home/shiny/data/log2UNIC_crk_scenarioU.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py mat_scenarioL.rip &> /home/shiny/data/log2UNIC_mat_scenarioL.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py mat_scenarioAL.rip &> /home/shiny/data/log2UNIC_mat_scenarioAL.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py mat_scenarioD.rip &> /home/shiny/data/log2UNIC_mat_scenarioD.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py lcc_scenarioAG.rip &> /home/shiny/data/log2UNIC_lcc_scenarioAG.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py mat_scenarioC.rip &> /home/shiny/data/log2UNIC_mat_scenarioC.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py crk_scenarioV.rip &> /home/shiny/data/log2UNIC_crk_scenarioV.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py lcc_scenarioAL.rip &> /home/shiny/data/log2UNIC_lcc_scenarioAL.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py mat_scenarioK.rip &> /home/shiny/data/log2UNIC_mat_scenarioK.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py lcc_scenarioAO.rip &> /home/shiny/data/log2UNIC_lcc_scenarioAO.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py mat_scenarioX.rip &> /home/shiny/data/log2UNIC_mat_scenarioX.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py mat_scenarioQ.rip &> /home/shiny/data/log2UNIC_mat_scenarioQ.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py crk_scenarioS.rip &> /home/shiny/data/log2UNIC_crk_scenarioS.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py crk_scenarioG.rip &> /home/shiny/data/log2UNIC_crk_scenarioG.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py crk_scenarioK.rip &> /home/shiny/data/log2UNIC_crk_scenarioK.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py mat_scenarioJ.rip &> /home/shiny/data/log2UNIC_mat_scenarioJ.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py crk_scenarioM.rip &> /home/shiny/data/log2UNIC_crk_scenarioM.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py crk_scenarioZ.rip &> /home/shiny/data/log2UNIC_crk_scenarioZ.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py lcc_scenarioAD.rip &> /home/shiny/data/log2UNIC_lcc_scenarioAD.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py lcc_scenarioAC.rip &> /home/shiny/data/log2UNIC_lcc_scenarioAC.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py crk_scenarioAF.rip &> /home/shiny/data/log2UNIC_crk_scenarioAF.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py mat_scenarioE.rip &> /home/shiny/data/log2UNIC_mat_scenarioE.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py crk_scenarioT.rip &> /home/shiny/data/log2UNIC_crk_scenarioT.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py mat_scenarioAJ.rip &> /home/shiny/data/log2UNIC_mat_scenarioAJ.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py crk_scenarioY.rip &> /home/shiny/data/log2UNIC_crk_scenarioY.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py mat_scenarioI.rip &> /home/shiny/data/log2UNIC_mat_scenarioI.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py crk_scenarioO.rip &> /home/shiny/data/log2UNIC_crk_scenarioO.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py lcc_scenarioAK.rip &> /home/shiny/data/log2UNIC_lcc_scenarioAK.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py lcc_scenarioAM.rip &> /home/shiny/data/log2UNIC_lcc_scenarioAM.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py crk_scenarioE.rip &> /home/shiny/data/log2UNIC_crk_scenarioE.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py mat_scenarioF.rip &> /home/shiny/data/log2UNIC_mat_scenarioF.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py mat_scenarioU.rip &> /home/shiny/data/log2UNIC_mat_scenarioU.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py mat_scenarioP.rip &> /home/shiny/data/log2UNIC_mat_scenarioP.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py mat_scenarioY.rip &> /home/shiny/data/log2UNIC_mat_scenarioY.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py crk_scenarioX.rip &> /home/shiny/data/log2UNIC_crk_scenarioX.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py crk_scenarioAO.rip &> /home/shiny/data/log2UNIC_crk_scenarioAO.txt
taskset --cpu-list 6 /usr/bin/time -v /home/shiny/anaconda3/envs/cdujlab/bin/python UNICOR.py crk_scenarioN.rip &> /home/shiny/data/log2UNIC_crk_scenarioN.txt
