FROM continuumio/miniconda3:latest

# Install mongo prerequisites
#RUN docker search continuumio
#RUN docker pull continuumio/miniconda3

RUN conda create -n cdujlab networkit networkx h5py pip ipykernel ipywidgets pandas geopandas jupyterlab nb_conda_kernels jupyter_contrib_nbextensions ipysheet -c conda-forge -y 

RUN conda activate cdujlab
RUN git clone https://github.com/ComputationalEcologyLab/CDPOP.git && git clone https://github.com/ComputationalEcologyLab/UNICOR.git 

RUN mkdir /opt/notebooks 
RUN mkdir /dockerdata

# Copy everything from the current directory into the container
COPY / /

# open port 8888 to traffic
EXPOSE 8888
