FROM continuumio/miniconda3:latest

# Install mongo prerequisites
#RUN docker search continuumio
#RUN docker pull continuumio/miniconda3

RUN conda create -n cdujlab networkit networkx h5py pip ipykernel ipywidgets pandas geopandas jupyterlab nb_conda_kernels jupyter_contrib_nbextensions ipysheet -c conda-forge -y 

RUN mkdir /opt/notebooks 
RUN mkdir /dockerdata
WORKDIR /dockerdata

# https://docs.streamlit.io/knowledge-base/tutorials/deploy/docker
RUN cd /dockerdata
RUN pwd

#RUN conda activate cdujlab
RUN git clone https://github.com/ComputationalEcologyLab/CDPOP.git && git clone https://github.com/ComputationalEcologyLab/UNICOR.git

RUN pip install pandas ipywidgets ipysheet streamlit

RUN wget https://raw.githubusercontent.com/rbachati/cdpop_mui/main/test.py

#RUN streamlit run dockerdata/test.py


# Copy everything from the current directory into the container
COPY / /

# open port 8501 to traffic
EXPOSE 8501

ENTRYPOINT ["streamlit", "run", "test.py", "--server.port=8501", "--server.address=0.0.0.0"]
